FROM node:lts AS development

WORKDIR /app/iewa

COPY package*.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "start:dev"]

FROM node:lts AS production

WORKDIR /usr/src/iewa

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD [ "node", "dist/main.js" ]

