version: '3.9'

services:

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email irovler@gmail.com -d api.iewa.io --agree-tos

  iewa-backend:
    build:
      context: ./
      dockerfile: DockerFile
      target: production
    ports:
      - "3000:3000"
    image: iewa-backend
    container_name: iewa-backend
    networks:
      iewa_network:
        aliases:
          - iewa-backend
    volumes:
      - .:/app/iewa
      - /app/iewa/node_modules



  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - iewa_network
    environment:
      - POSTGRES_USER=iewa-test
      - POSTGRES_PASSWORD=iewa-test
      - POSTGRES_DB=iewa-test

  nginx:
    build:
      context: ./
      dockerfile: DockerFileNginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build/:/usr/share/nginx/html
      - ./certs:/etc/letsencrypt
    depends_on:
      - certbot
      - iewa-backend
    networks:
      - iewa_network


networks:
  iewa_network:
    driver: bridge
    attachable: true

volumes:
  postgres_data:
    driver: local
